# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        log_file: pre-commit.log
    -   id: end-of-file-fixer
        log_file: pre-commit.log
    -   id: check-yaml
        log_file: pre-commit.log
    -   id: check-added-large-files
        log_file: pre-commit.log
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: master
    hooks:
    -   id: clang-format
        args: [--style=Google, --sort-includes=false]
        log_file: pre-commit-cpp.log
    -   id: cpplint
        args: [--filter=-build/include_subdir, --exclude=udon2_cpp_src/map_indexing_suite_v2.hpp]
        log_file: pre-commit-cpp.log
    -   id: cppcheck
        args: [--std=c++11, --language=c++]
        log_file: pre-commit-cpp.log
